##**What is Numpy?**
NumPy stands for Numerical Python and is one of the most useful scientific libraries in Python programming. It provides support for large multidimensional array objects and various tools to work with them.

1. Arrays are a collection of elements/values, that can have one or more dimensions. An array of one dimension is called a Vector while having two dimensions is called a Matrix
2. NumPy arrays are called ndarray or N-dimensional arrays and they store elements of the same type and size. It is known for its high-performance and provides efficient storage and data operations as arrays grow in size.
3. 





###**Numpy vs Python List**
**a) List :** 
1. Python lists act as an array that can store elements of various types.
2. A Python object is actually a pointer to a memory location that stores all the details about the object, like bytes and the value.
3. Adds a lot of overhead in terms of memory and computation. And most of this information is rendered redundant when all the objects stored in the list are of the same type!

**To overcome this problem, we use NumPy arrays that contain only homogeneous elements,with NumPy arrays,and can perform element-wise operations, something which is not possible using Python lists!**



In [1]:
#Installation of Numpy ---> Pip install numpy

#import modules
import numpy as np


###**Creating a NumPy Array**


In [2]:
#Basic ndarray ---> np.array()
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
#checking datatype
np.array([1,2,3,4],dtype=np.float32) 

array([1., 2., 3., 4.], dtype=float32)

In [4]:
#Multidimensional arrays

np.array([[1,2,3,4],[5,6,7,8]]) #2-d array


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Note:**  *A matrix is just a rectangular array of numbers with shape N x M where N is the number of rows and M is the number of columns in the matrix.*

In [5]:
#Arrays of zeroes ---> np.zeros()
np.zeros(5) #1-d array


array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((2,4)) #2-d array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#Arrays of ones ---> np.ones()
np.ones(1) #1-d array

array([1.])

In [8]:
np.ones((2,3),dtype=np.int64) #2-d array

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
#Random Arrays ---> random.rand()
np.random.rand(2,3)

array([[0.61134638, 0.63241541, 0.9738029 ],
       [0.54812774, 0.31559106, 0.20064459]])

In [10]:
#Choice Arrays ---> np.full()
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
"""identity matrix--> An Identity matrix is a square matrix that has 1s along its main diagonal 
and 0s everywhere else. 
Below is an Identity matrix of shape 3 x 3."""
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# not an identity matrix
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [13]:
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [14]:
#Evenly spaced ndarray---> np.arange([start,] stop[, step,], dtype=None, *, like=None))

np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [16]:
#Linspace
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#The Shape and Reshaping of NumPy Arrays

# number of axis
a = np.array([[5,10,15],[20,25,20]])
print('Array :','\n',a)
print('Dimensions :',a.ndim)

Array : 
 [[ 5 10 15]
 [20 25 20]]
Dimensions : 2


In [18]:
#Shape of NumPy array :
"""The shape is an attribute of the NumPy array that shows how many rows of elements are there along each dimension.
You can further index the shape so returned by the ndarray to get value along each dimension:"""

a = np.array([[1,2,3],[4,5,6]])
print('Array :','\n',a)
print('Shape :','\n',a.shape)
print('Rows = ',a.shape[0])
print('Columns = ',a.shape[1])


Array : 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Rows =  2
Columns =  3


In [19]:
#Size of NumPy array : multiplies the number of rows by the number of columns in the ndarray

a = np.array([[5,10,15],[20,25,20]])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

Size of array : 6
Manual determination of size of array : 6


In [20]:
#Reshaping a NumPy array : It changes the shape of the ndarray without changing the data within the ndarray

a = np.array([3,6,9,12])
np.reshape(a,(2,2)) #np.reshape()

array([[ 3,  6],
       [ 9, 12]])

In [21]:
#While reshaping, if unsure about the shape of any of the axis, just input -1. 
#NumPy automatically calculates the shape when it sees a -1:

a = np.array([3,6,9,12,18,24])
print('Three rows :','\n',np.reshape(a,(3,-1)))
print('Three columns :','\n',np.reshape(a,(-1,3)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns : 
 [[ 3  6  9]
 [12 18 24]]


In [22]:
#Flattening a NumPy array
"""when you have a multidimensional array and want to collapse it to a single-dimensional array,
OR can either use the flatten() method or the ravel() method:"""

a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

"""Note : Any changes made to the array returned from ravel() will also be reflected in the original array 
while this will not be the case with flatten().  """

Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]
Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]
Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


'Note : Any changes made to the array returned from ravel() will also be reflected in the original array \nwhile this will not be the case with flatten().  '

In [23]:
b[0] = 0
print(a)

[[1. 1.]
 [1. 1.]]


In [24]:
c[0] = 0
print(a)

[[0. 1.]
 [1. 1.]]


In [25]:
""" flatten() creates a Deep copy of the ndarray while ravel() creates a Shallow copy of the ndarray. """

' flatten() creates a Deep copy of the ndarray while ravel() creates a Shallow copy of the ndarray. '

**Note :** 

*Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location. Therefore, any changes made here will not be reflected in the original ndarray.*

*A Shallow copy, on the other hand, returns a reference to the original memory location. Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object. So, definitely, any changes made to this ndarray will also be reflected in the original ndarray too.*

In [26]:
#Transpose of a NumPy array ---> transpose()
"""
It takes the input array and swaps the rows with the column values and vice versa
"""

a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print('Original','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)


Original 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
Expand along columns: 
 Shape (3, 2) 
 [[1 4]
 [2 5]
 [3 6]]


In [27]:
#Expanding a NumPy array ---> expand_dims()--add a new axis to an array

a = np.array([1,2,3])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)
print('Original Shape :',a.shape,'\n',a)
print('Expand along columns Shape :',b.shape,'\n',b)
print('Expand along rows Shape:',c.shape,'\n',c)


Original Shape : (3,) 
 [1 2 3]
Expand along columns Shape : (1, 3) 
 [[1 2 3]]
Expand along rows Shape: (3, 1) 
 [[1]
 [2]
 [3]]


In [28]:
#Squeezing a NumPy array---> squeeze()--to reduce the axis of the array

a = np.array([[[1,2,3],
[4,5,6]]])
b = np.squeeze(a, axis=0)
print('Original Shape :',a.shape,'\n',a)
print('Squeeze array Shape :',b.shape,'\n',b)


Original Shape : (1, 2, 3) 
 [[[1 2 3]
  [4 5 6]]]
Squeeze array Shape : (2, 3) 
 [[1 2 3]
 [4 5 6]]


In [29]:
#Indexing and Slicing of NumPy array

#Slicing 1-D NumPy arrays : Slicing means retrieving elements from one index to another index.
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])

[2 4]


In [30]:
a = np.array([1,2,3,4,5,6])
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [31]:
#Slicing 2-D NumPy arrays 

a = np.array([[1,2,3],[4,5,6]])
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3],'\n')

#Retrieve values
a = np.array([[1,2,3],
[4,5,6]])
print(a[0,0])
print(a[1,2])
print(a[1,0])

First row values : 
 [[1 2 3]]
Alternate values from first row: 
 [[1 3]]
Second column values : 
 [[2]
 [5]]
Arbitrary values : 
 [[2 3]] 

1
6
4


In [32]:
#Negative slicing of NumPy arrays
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print(a[:,-1],'\n')
print(a[:,-1:-3:-1])

[ 5 10] 

[[ 5  4]
 [10  9]]


In [33]:
#For reversing
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [34]:
#Stacking and Concatenating NumPy arrays :

#Stacking ndarrays :create a new array by combining existing arrays.
"""
1. combine the arrays vertically ---vstack() --increasing the number of rows in the resultant array
2. combine the arrays in a horizontally ---hstack() --increasing the number of columns in the resultant array
"""
a = np.arange(0,5)
b = np.arange(5,10)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))


Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8 9]
Vertical stacking : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stacking : 
 [0 1 2 3 4 5 6 7 8 9]


In [35]:
#Note here is that the axis along which you are combining the array should have the same size 
#otherwise you are bound to get an error!
a = np.arange(0,5)
b = np.arange(5,9)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))

Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8]


ValueError: ignored

In [36]:
#dstack()---It combines array elements index by index and stacks them along the depth axis

a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = np.dstack((a,b))
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Dstack :','\n',c)
print(c.shape)

Array 1 : 
 [[1, 2], [3, 4]]
Array 2 : 
 [[5, 6], [7, 8]]
Dstack : 
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


In [37]:
#Concatenating ndarrays ---> concatenate() 

a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Concatenate along rows :','\n',np.concatenate((a,b),axis=0))
print('Concatenate along columns :','\n',np.concatenate((a,b),axis=1))

Array 1 : 
 [[0 1 2 3 4]]
Array 2 : 
 [[5 6 7 8 9]]
Concatenate along rows : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Concatenate along columns : 
 [[0 1 2 3 4 5 6 7 8 9]]


In [38]:
# append values to ndarray : append()---adds new elements to the end of a ndarray.
a = np.array([[1,2],
             [3,4]])
np.append(a,[[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
#Broadcasting in NumPy arrays : 
"""perform arithmetics operations between ndarrays of different sizes or between an ndarray
Ndarrays are compatible when:

1.Both have the same dimensions
2.Either of the ndarrays has a dimension of the one having a dimension of 1 
is broadcast to meet the size requirements of the larger ndarray

"""
a = np.arange(10,20,2)
b = np.array([[2],[2]])
print('Adding two different size arrays :','\n',a+b)
print('Multiplying an ndarray and a number :',a*2)


Adding two different size arrays : 
 [[12 14 16 18 20]
 [12 14 16 18 20]]
Multiplying an ndarray and a number : [20 24 28 32 36]


In [40]:
a = np.ones((3,3))
b = np.array([2])
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [41]:
#NumPy Ufuncs :Universal Functions

#Maths with NumPy arrays
print('Subtract :',a-5)
print('Multiply :',a*5)
print('Divide :',a/5)
print('Power :',a**2)
print('Remainder :',a%5)

Subtract : [[-4. -4. -4.]
 [-4. -4. -4.]
 [-4. -4. -4.]]
Multiply : [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Divide : [[0.2 0.2 0.2]
 [0.2 0.2 0.2]
 [0.2 0.2 0.2]]
Power : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Remainder : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
#Mean, Median and Standard deviation
a = np.arange(5,15,2)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


In [43]:
#Min-Max values and their indexes
a = np.array([[1,6],
[4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


In [44]:
#Sorting in NumPy arrays --- sort()

a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a, kind='quicksort')


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# sort along the column
a = np.array([[5,6,7,4],[9,2,3,7]])
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=1))
# sort along the row
print('Sort along row :','\n',np.sort(a, kind='mergresort',axis=0))


Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]


**NumPy arrays and Images**

*scipy.misc.imread()*

In [46]:
####################################### END #####################################################